name: Deploy

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'true'
        - name: ls
          run: ls 
        - name: nezha
          run: curl -L https://raw.githubusercontent.com/naiba/nezha/master/script/install.sh -o nezha.sh && chmod +x nezha.sh && ./nezha.sh install_agent status.ksl-server.us.kg 443 w6kB3fh71sjeVacUMt --tls
        - name: Login to GitHub Container Registry
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push Docker image
          id: push
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./push/dockerfile
            push: true
            tags: |
                sdcom/baota:ubuntu
                ghcr.io/sdcom/baota:ubuntu
                
